
language: node_js

env:
  - DATABASE_TEST=mongodb://localhost/testing

node_js:
  - "stable"

services:
  - mongodb

cache:
  npm: false

script:
  - cd server/
  - npm ci
  - npm test
  - npm run coverage

after_success:
  - npm run coveralls